### ISSUE TITLE
안녕, 깃허브 액션 행성 - 대륙

### ISSUE THREAD

**Issue by bryantson** [githubuniverseworkshops/GitHub-Actions-Planet-2021-Korea#1]
# 안녕, 깃허브 액션 행성

![1_HelloGitHubActions](https://user-images.githubusercontent.com/5396174/138540486-9672e8a8-9e6d-43a1-a115-93777385cee7.jpg)

> 이 행성의 신은 여러분의 여행이 유익하고 즐겁길 바랍니다. 하지만 긴 여정을 떠나기 전에 깃허브 액션 행성에 감사 표현을 하면 더 좋겠죠

## 주어진 미션

- [ ] 깃허브 액션에 관해서 배워봐요
- [ ] 액티비티 - 첫 깃허브 액션 스크립트를 같이 만들어 봐요

# 깃허브 액션에 관해서 배워봐요

## 깃허브 액션 - 기본 수업

깃허브 액션은 워크플로우를 자동화 시켜주는 깃허브 서비스 입니다

![image](https://user-images.githubusercontent.com/5396174/138026868-5d2bd88f-1666-4cb0-8a86-9cba05e4ecdd.png)

- 워크플로우는 YML 파일로 저장 됩니다
- 깃허브 안에 완벽하게 내재되어 있습니다
- 깃허브 이벤트에 반응 합니다
- 라이브 로그와 워크플로우 실행를 시각화 합니다
- 워크플로우는 커뮤니티가 직접 기여할수 있습니다
- 깃허브 제공 기본 러너가 기본으로 제공 되지만 직접 호스팅하는 러너를 쓸수 있습니다
- 암호나 시크릿을 저장할수 있는 기능이 내재되어 있습니다

## 깃허브 액션 마켓플레이스

![image](https://user-images.githubusercontent.com/5396174/138026785-f253a1d1-4e64-4cd8-942a-5f22aca58f16.png)

- 다양한 피일드를 카버하는 오픈소스 액션들을 찾으실수 있습니다
- 현재 10,000 개가 넘는 액션이 있습니다 (계속 증가 중입니다) 
- 대기업이 만든 안전하고 인증된 플러그인도 찾을수 있습니다
- 워크플로우에 이 액션들을 직접 레퍼런스 할수 있습니다
- 깃허브 에디터에 자동적으로 내재되어 있습니다

## 깃허브 액션의 아키텍쳐

![image](https://user-images.githubusercontent.com/5396174/138027157-4d1953f9-002c-4731-b432-c708bd3a0248.png)

## 기본 문법

```yaml

# 워크플로우 이름을 나타냅니다
name: Super Linter 워크플로우

# 어떤 이벤트에 트리거 되는지 정의 합니다. 이 경우에는 깃허브 푸쉬 이벤트에 반응 합니다:
on:
  push:

# 다양한 잡들을 설정합니다
jobs:
  # 다른곳에서 레퍼런스 하기위한 이름입니다
  lint:
     # 사람이 읽을수 있는 잡 이름을 더합니다
     name: Lint Code Base

     # 러너를 설정합니다. 이 경우에는  깃허브 제공 기본 러너 중 하나인 Ubuntu 의 최신 버전을 씁니다:
     runs-on: ubuntu-latest

     # 다양한 스텝을 정의 합니다:
     steps:
        # 먼저, 레포에서 체크 아웃 합니다:
        - uses: actions/checkout@v2
        # Super Linter 깃허브 액션 플러그인 를 씁니다
        - uses: github/super-linter@v3
           env:
              # 깃허브 시크릿을 읽어서 사용합니다:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

#  액티비티 - 첫 깃허브 액션 스크립트를 같이 만들어 봐요

깃허브 액션 행성에게 다음 메시지로 정식으로 인사를 하는 깃허브 액션 스크립트를 만들어 볼것 입니다:

> 따뜻한 환영 고마워요! 저의 이름은 xxx 입니다
> 신비로운 깃허브 액션에서 즐거운 시간을 보낼께요!

미션을 완성하기 위해선 보이는 설명을 따라 합니다:

1. 스크립트를 복사 한 후 노트패드 에디터에 잠시 저장 합니다
2. `username` 이 본인 깃허브 아이디인 `hello-username` 이란 깃허브 브랜치를 만듭니다
3. `.github/workflows` 디렉토리에 가서 **Add file** 버튼을 누릅니다.  `username` 이 본인 깃허브 아이디인 `action-hello-username.yml` 과 같이 파일 이름을 만들고 커밋해서 브랜치에 푸쉬 합니다.
4. `main` 브랜치에 풀리퀘스트 (PR) 합니다.
5. 누군가 리뷰를 합니다.
6.  `main` 브랜치에 merge 되면 깃허브 액션을 돌리실수 있습니다.

```yaml
name: 안녕, 깃허브 액션

on:
  workflow_dispatch:
      inputs:
         myName:
            description: "이름을 입려해 주세요"
            required: true
            default: ''

jobs:
   Hello-GitHub-Actions:
      runs-on: ubuntu-latest
      name: 그냥 "안녕" 인사하고 싶었어요 ^^

      steps:
        - name: 안녕하세요, 깃허브 액션
          run: |
             echo "따뜻한 환영 고마워요! 저의 이름은 ${{ github.event.inputs.myName }} 입니다"
             echo "신비로운 깃허브 액션에서 즐거운 시간을 보낼께요!"
```
