### ISSUE TITLE
메시지 전송 - 대륙

### ISSUE THREAD

**Issue by bryantson** [githubuniverseworkshops/GitHub-Actions-Planet-2021-Korea#5]
# 메시지 전송 대륙에 오신걸 환영 합니다

![5_SendMessage](https://user-images.githubusercontent.com/5396174/138540839-defaf1b4-e5d7-4ce1-832b-44ed4b76b4ee.jpg)

> 데브옵스 대륙으로 가는 망망대해를 건너기 전해 지구에 있는 가족과 친구들에게 깃허브 액션 행성에서 잘 지내고 있고 즐겁게 보내고 있다는 안부 메시지를 전송 하는건 어떨까요?

## 주어진 미션

- [x] 메시지를 전송하게 해주는 여러가지 깃허브 액션 플러그인에 관해서 배워봐요
- [x] 액티비티 - 슬랙과 마이크로소프트 팀즈를 통해서 메시지를 보내봐요

# 메시지를 전송하게 해주는 여러가지 깃허브 액션 플러그인에 관해서 배워봐요

**깃허브 액션 마켓플레이스** 에서 메시지를 전송하거나 알림을 줄수 있는 다야한 깃허브 액션 플러그인을 찾으실 수 있습니다.

![image](https://user-images.githubusercontent.com/5396174/138631391-d10c3682-8228-425e-81b9-f120f121f004.png)

예를 들어 `slackapi/slack-github-action` 깃허브 액션 플러그인을 통해서 슬랙 메시지를 보낼수 있습니다.

```yaml
- name: 슬랙 채널에 메시지 보내기
  id: slack
  uses: slackapi/slack-github-action@v1.14.0
  with:
    channel-id: 'CHANNEL_ID'  # 슬랙 채널 ID
    slack-message: '깃허브 액션에서 메시지 전송!'
  env:
    SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
```

 **Twilio** 를 통해서 SMS 문자 메시지를 보내는 방법도 있습니다!

```yaml
- name: 'SMS 문자 메시지 보내기'
  uses: twilio-labs/actions-sms@v1
  with:
    fromPhoneNumber: '+1(234)5678901'
    toPhoneNumber: '+1(234)3334444'
    message: 'Twilio 에서 안녕'
  env:
    TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
    TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
    TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
```

## 액티비티 - 슬랙과 마이크로소프트 팀즈를 통해서 메시지를 보내봐요

깃허브 액션 행성에서 슬랙과 마이크로소프트 팀즈를 통해서 안부 메시지를 전송 할것 입니다. 그러기 위해서 `.github/workflows` 에 이미 만들어진 깃허브 액션 파이프라인 스크립트를 활용 할수 있습니다:

- `action-send-slack-msg.yml`: 다음 깃허브 액션 파이프라인 스크립트로 슬랙 메시지를 보낼수 있습니다. 슬랙앱을 만들어서 We can use `chat:write` 권한이 있는 **봇 토큰** 을 만들어서 깃허브 시크릿에 저장 합니다
- `action-send-team-msg.yml`: 다음 깃허브 액션 파이프라인 스크립트로 마이크로스프 팀즈 메시지를 보낼수 있습니다.  이 플러그 인은 팀즈 웹훅 (Webhook) 링크만 필요합니다!

## ⏭️  다 끝난 후 여기 깃허브 이슈를 닫으시면 그 다음 깃허브 이슈 미션이 주어질 것입니다
